/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DevBalcoreRouteImport } from './routes/dev/balcore'
import { Route as ApiAccessRedeemRouteImport } from './routes/api/access/redeem'
import { Route as ApiAccessVerifyRouteImport } from './routes/api/access/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBalcoreRoute = DevBalcoreRouteImport.update({
  id: '/dev/balcore',
  path: '/dev/balcore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessRedeemRoute = ApiAccessRedeemRouteImport.update({
  id: '/api/access/redeem',
  path: '/api/access/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessVerifyRoute = ApiAccessVerifyRouteImport.update({
  id: '/api/access/verify',
  path: '/api/access/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/dev/balcore': typeof DevBalcoreRoute
  '/api/access/redeem': typeof ApiAccessRedeemRoute
  '/api/access/verify': typeof ApiAccessVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/dev/balcore': typeof DevBalcoreRoute
  '/api/access/redeem': typeof ApiAccessRedeemRoute
  '/api/access/verify': typeof ApiAccessVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/dev/balcore': typeof DevBalcoreRoute
  '/api/access/redeem': typeof ApiAccessRedeemRoute
  '/api/access/verify': typeof ApiAccessVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorer'
    | '/dev/balcore'
    | '/api/access/redeem'
    | '/api/access/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorer'
    | '/dev/balcore'
    | '/api/access/redeem'
    | '/api/access/verify'
  id:
    | '__root__'
    | '/'
    | '/explorer'
    | '/dev/balcore'
    | '/api/access/redeem'
    | '/api/access/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRoute: typeof ExplorerRoute
  DevBalcoreRoute: typeof DevBalcoreRoute
  ApiAccessRedeemRoute: typeof ApiAccessRedeemRoute
  ApiAccessVerifyRoute: typeof ApiAccessVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/balcore': {
      id: '/dev/balcore'
      path: '/dev/balcore'
      fullPath: '/dev/balcore'
      preLoaderRoute: typeof DevBalcoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access/redeem': {
      id: '/api/access/redeem'
      path: '/api/access/redeem'
      fullPath: '/api/access/redeem'
      preLoaderRoute: typeof ApiAccessRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access/verify': {
      id: '/api/access/verify'
      path: '/api/access/verify'
      fullPath: '/api/access/verify'
      preLoaderRoute: typeof ApiAccessVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRoute: ExplorerRoute,
  DevBalcoreRoute: DevBalcoreRoute,
  ApiAccessRedeemRoute: ApiAccessRedeemRoute,
  ApiAccessVerifyRoute: ApiAccessVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
